name: infoload
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  file_picker: ^8.0.6
  json_annotation: ^4.8.0
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.11
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_database: ^11.0.4
  firebase_storage: ^12.1.2
  firebase_analytics: ^11.2.1
  firebase_messaging: ^15.0.4
  http: ^1.2.2
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0
  logger: ^2.4.0
  intl: ^0.19.0
  excel: ^4.0.2
  csv: ^6.0.0
  archive: ^3.6.1
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
